### ISSUE TITLE
Where are the backend logs?

### ISSUE THREAD

**Issue by vilaca** [nstuyvesant/sveltekit-auth-example#10]
How do I turn on logging or change the logging level of the backend and where/how can I see the logs?

**Comment by nstuyvesant** [comment]
That would be outside the scope of this example project. Logging could be at the API or database level. There are dozens of approaches. Here's an article I found using Google...
https://jeffmcmorris.medium.com/awesome-logging-in-sveltekit-6afa29c5892c

Generally, the place to log API calls would be in hooks.server.ts...
https://kit.svelte.dev/docs/hooks
