### ISSUE TITLE
Could not communicate with database

### ISSUE THREAD

**Issue by ryanbuckleyca** [nstuyvesant/sveltekit-auth-example#12]
I'm pretty sure this is just a set-up issue, but I followed your directions in the readme, so I'm assuming others might have a similar issue and so whatever solution comes from this could help them too, or maybe we'll find a step that was misunderstood and can add some clearer language around it.

I've set-up my .env with my postgres credentials, and have tested them using the `psql` command to make sure.

I run the `psql -d postgres -f db_create.sql` command and all seems good.

following-up with `yarn dev -- --open` i go to the login page and try one of the email/password from the readme but i get the "Could not communicate with database" error.

<img width="552" alt="Screenshot 2023-12-11 at 4 15 11 PM" src="https://github.com/nstuyvesant/sveltekit-auth-example/assets/48371025/44e2d8ba-c3c6-4c77-b2ff-e1ab721a99e1">

My list of databases show that `auth` has been created from the script:
```
                                                       List of databases
           Name            | Owner | Encoding | Locale Provider | Collate | Ctype | ICU Locale | ICU Rules | Access privileges 
---------------------------+-------+----------+-----------------+---------+-------+------------+-----------+-------------------
 auth                      | auth  | UTF8     | libc            | C       | C     |            |           | 
```

Not sure what sort of postgres configuration might be mixed up here but hopefully it's an easy solution.

Thanks!

**Comment by nstuyvesant** [comment]
Not 100% sure this is a database issue. The line that is erroring is sending a POST to the vite dev server. Does anything get logged in the terminal window where you invoked `yarn dev -- --open`? If not, the connection to http://localhost:3000/auth/login may be getting blocked (local firewall?).

You could add a console.log to src/routes/auth/[slug]/+server.ts before line 12 to see if the dev server is even getting the POST.
