### ISSUE TITLE
production build fails

### ISSUE THREAD

**Issue by orefalo** [nstuyvesant/sveltekit-auth-example#2]
hi, just reporting this issue here - `yarn build` fails with:

```
> Using @sveltejs/adapter-node
Error: Cannot access url.searchParams on a page with prerendering enabled
```

I believe I found solutions here - didn't try yet.
https://github.com/sveltejs/kit/issues/3173

**Comment by nstuyvesant** [comment]
Yep - API for SvelteKit changed. Small fix.

**Comment by nstuyvesant** [comment]
Try out 1.0.2 and let me know if that solves your issue.

**Comment by nstuyvesant** [comment]
Will close for now as I'm pretty sure 1.0.2 fixes. Can always reopen this.

**Comment by orefalo** [comment]
it works, ty

**Comment by nstuyvesant** [comment]
Terrific - thanks for confirming!
