### ISSUE TITLE
Cache issue?

### ISSUE THREAD

**Issue by adadion** [nstuyvesant/sveltekit-auth-example#7]
In the same browser & device.

My root route, displaying user's first name and last name.

User John Doe login, home displaying John Doe. Then logout.
User Lorem Ipsum login, home still displaying John Doe.

Somehow, user John Doe info still persist, so I need to Hard Reload the browser (ctrl+shift+r), then home correctly displaying Lorem Ipsum.

**Comment by nstuyvesant** [comment]
Having difficulty reproducing your issue. Here are the steps I tried:

1. `npm run dev`
2. Opened Safari 16.1 to http://localhost:3000
3. Clicked **Login** at top right
4. Entered **admin@example.com** for the **Email** field and **admin123** for the **Password**.
5. Navigated to **Home**
6. Selected **Avatar menu** -> **Logout**
7. Navigated to **Home**
8. Repeated steps 3-7 using **teacher@example.com** password **teacher123**

This is what it looked like (showing it was logged out correctly)...

<img width="460" alt="image" src="https://user-images.githubusercontent.com/5770938/200120528-b600a3af-e473-4c04-b756-d0ec19dc1860.png">

Can you share which web browser and version you are using? Also, what version of this project are you on? I would recommend getting the latest version of the project if you do not have 1.0.32 as of this note.

**Comment by nstuyvesant** [comment]
Hi - any updates?

**Comment by adadion** [comment]
Sorry, it has nothing to do with this repo, it's on my modification.
